'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import Link from 'next/link';
import './relations.css';
type Album={id:string;title:string;artist:string;year:number|null;releaseType:string;language:string|null;durationSeconds:number|null;trackCount:number;userRating:number|null;communityRating:number|null;ratingCount:number;ranks:{position:number;scope:string}[];genres:string[];descriptors:string[];cover:string;url:string|null;visual?:{accent?:{h:number;s:number;l:number};dominant?:{h:number;s:number;l:number}}};
type Point={x:number;y:number;z:number};type Camera={x:number;y:number;scale:number;rotation:number};
const hash=(s:string,n=0)=>{let h=2166136261^n;for(const c of s)h=Math.imul(h^c.charCodeAt(0),16777619);return((h>>>0)%10007)/10007},overlap=(x:string[],y:string[])=>x.filter(v=>y.includes(v)).length/Math.max(1,new Set([...x,...y]).size),accentSimilarity=(a:Album,b:Album)=>{const x=a.visual?.accent??a.visual?.dominant,y=b.visual?.accent??b.visual?.dominant;if(!x||!y)return.5;const hueGap=Math.min(Math.abs(x.h-y.h),360-Math.abs(x.h-y.h))/180;return 1-(hueGap*.62+Math.abs(x.s-y.s)/100*.24+Math.abs(x.l-y.l)/100*.14)},similarity=(a:Album,b:Album)=>overlap(a.genres,b.genres)*.47+overlap(a.descriptors,b.descriptors)*.25+(1-Math.min(1,Math.abs((a.year||2000)-(b.year||2000))/50))*.1+accentSimilarity(a,b)*.18;
export default function RelationsPage(){
 const [all,setAll]=useState<Album[]>([]),[focus,setFocus]=useState<Album|null>(null),[mode,setMode]=useState<'2d'|'3d'>('2d'),[camera,setCamera]=useState<Camera>({x:0,y:0,scale:1,rotation:20}),[trail,setTrail]=useState<string[]>([]),[query,setQuery]=useState(''),[manual,setManual]=useState<Record<string,Point>>({}),[clock,setClock]=useState(0);
 const world=useRef<HTMLDivElement>({clientWidth:0,clientHeight:0} as HTMLDivElement),gesture=useRef<{points:Map<number,{x:number;y:number}>;start?:Camera;distance?:number;center?:{x:number;y:number};drag?:{id:string;x:number;y:number;start:Point}}>({points:new Map()});
 useEffect(()=>{fetch('/data/albums.json').then(r=>r.json() as Promise<Album[]>).then(setAll)},[]);const albums=useMemo(()=>[...all].sort((a,b)=>b.ratingCount-a.ratingCount).filter((_,i)=>i<180||i%Math.max(1,Math.floor(all.length/80))===0).slice(0,240),[all]);
 const edges=useMemo(()=>albums.flatMap((a,i)=>albums.map((b,j)=>[j,j===i?-1:similarity(a,b)] as [number,number]).sort((x,y)=>y[1]-x[1]).slice(0,3).filter(([j])=>i<j).map(([j])=>[i,j] as [number,number])),[albums]);
 const base=useMemo(()=>{const p=albums.map(a=>({x:(hash(a.id,4)-.5)*1500,y:(hash(a.id,9)-.5)*1050,z:(hash(a.id,13)-.5)*700}));for(let t=0;t<80;t++){const f=p.map(()=>({x:0,y:0}));for(let i=0;i<p.length;i++)for(let j=i+1;j<p.length;j++){const dx=p[j].x-p[i].x,dy=p[j].y-p[i].y,d2=Math.max(900,dx*dx+dy*dy),v=1200/d2;f[i].x-=dx*v;f[i].y-=dy*v;f[j].x+=dx*v;f[j].y+=dy*v}edges.forEach(([i,j])=>{const dx=p[j].x-p[i].x,dy=p[j].y-p[i].y,d=Math.max(1,Math.hypot(dx,dy)),v=(d-145)*.005;f[i].x+=dx/d*v;f[i].y+=dy/d*v;f[j].x-=dx/d*v;f[j].y-=dy/d*v});p.forEach((q,i)=>{q.x=(q.x+f[i].x)*.998;q.y=(q.y+f[i].y)*.998})}return Object.fromEntries(albums.map((a,i)=>[a.id,p[i]]));},[albums,edges]);
 useEffect(()=>{let frame=0,last=0;const animate=(now:number)=>{if(now-last>32){last=now;setClock(now/1000)}frame=requestAnimationFrame(animate)};frame=requestAnimationFrame(animate);return()=>cancelAnimationFrame(frame)},[]);
 const points={...base,...manual},project=(p:Point,id:string)=>{const moving=manual[id]?p:{...p,x:p.x+Math.sin(clock*.43+hash(id,21)*6.28)*7,y:p.y+Math.cos(clock*.37+hash(id,22)*6.28)*6,z:p.z+Math.sin(clock*.29+hash(id,23)*6.28)*9};if(mode==='2d')return{x:moving.x*.22,y:moving.y*.22,z:0};const yaw=camera.rotation*Math.PI/180,pitch=-.42,x1=moving.x*Math.cos(yaw)-moving.z*Math.sin(yaw),z1=moving.x*Math.sin(yaw)+moving.z*Math.cos(yaw),y1=moving.y*Math.cos(pitch)-z1*Math.sin(pitch),z2=moving.y*Math.sin(pitch)+z1*Math.cos(pitch),perspective=Math.max(.62,Math.min(1.55,900/(900-z2)));return{x:x1*perspective*.25,y:y1*perspective*.25,z:z2}},select=(a:Album)=>{setFocus(a);setTrail(t=>[...t.filter(id=>id!==a.id),a.id].slice(-16))},reset=()=>setCamera({x:0,y:0,scale:1,rotation:20}),zoom=(factor:number,cx=world.current?.clientWidth/2||0,cy=world.current?.clientHeight/2||0)=>setCamera(c=>{const scale=Math.max(.35,Math.min(3.5,c.scale*factor)),k=scale/c.scale;return{...c,scale,x:cx-(cx-c.x)*k,y:cy-(cy-c.y)*k}});
 const down=(e:React.PointerEvent,id?:string)=>{e.currentTarget.setPointerCapture?.(e.pointerId);const g=gesture.current;g.points.set(e.pointerId,{x:e.clientX,y:e.clientY});g.start={...camera};if(id&&e.pointerType!=='touch')g.drag={id,x:e.clientX,y:e.clientY,start:{...points[id]}};if(g.points.size===2){const q=[...g.points.values()];g.distance=Math.hypot(q[1].x-q[0].x,q[1].y-q[0].y);g.center={x:(q[0].x+q[1].x)/2,y:(q[0].y+q[1].y)/2};g.drag=undefined}},move=(e:React.PointerEvent)=>{const g=gesture.current,prev=g.points.get(e.pointerId);if(!prev)return;g.points.set(e.pointerId,{x:e.clientX,y:e.clientY});if(g.points.size===2&&g.distance&&g.start&&g.center){const q=[...g.points.values()],d=Math.hypot(q[1].x-q[0].x,q[1].y-q[0].y),c={x:(q[0].x+q[1].x)/2,y:(q[0].y+q[1].y)/2};setCamera({...g.start,scale:Math.max(.35,Math.min(3.5,g.start.scale*d/g.distance)),x:g.start.x+c.x-g.center.x,y:g.start.y+c.y-g.center.y});return}if(g.drag){const d=g.drag,projectionScale=mode==='2d'?.22:.25;setManual(m=>({...m,[d.id]:{...d.start,x:d.start.x+(e.clientX-d.x)/(camera.scale*projectionScale),y:d.start.y+(e.clientY-d.y)/(camera.scale*projectionScale)}}));return}setCamera(c=>({...c,x:c.x+e.clientX-prev.x,y:c.y+e.clientY-prev.y}))},up=(e:React.PointerEvent)=>{const g=gesture.current;g.points.delete(e.pointerId);g.drag=undefined;if(!g.points.size){g.start=undefined;g.distance=undefined}};
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.target as HTMLElement).matches('input'))return;if(e.key==='Escape')setFocus(null);if(e.key==='0')reset();if(e.key==='+'||e.key==='=')zoom(1.18);if(e.key==='-')zoom(.84);if(e.key.startsWith('Arrow')){e.preventDefault();setCamera(c=>({...c,x:c.x+(e.key==='ArrowLeft'?45:e.key==='ArrowRight'?-45:0),y:c.y+(e.key==='ArrowUp'?45:e.key==='ArrowDown'?-45:0)}))}};addEventListener('keydown',key);return()=>removeEventListener('keydown',key)},[]);const matches=query?all.filter(a=>`${a.title} ${a.artist}`.toLowerCase().includes(query.toLowerCase())).slice(0,7):[];
 return <main className="relationsPage"><header><Link href="/">← 返回图谱</Link><div><strong>关系漫游</strong><span>平移、缩放、拖拽节点并打开完整档案</span></div><nav><button className={mode==='2d'?'active':''} onClick={()=>setMode('2d')}>二维</button><button className={mode==='3d'?'active':''} onClick={()=>setMode('3d')}>三维景深</button></nav></header><div className="relationWorld" ref={world} tabIndex={0} onPointerDown={e=>down(e)} onPointerMove={move} onPointerUp={up} onPointerCancel={up} onWheel={e=>{e.preventDefault();zoom(Math.exp(-e.deltaY*.001),e.clientX,e.clientY)}}><div className="relationToolbar"><div className="relationSearch"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索专辑或艺术家"/>{matches.length>0&&<div>{matches.map(a=><button key={a.id} onClick={()=>{select(a);setQuery('')}}><img src={a.cover} alt=""/><span>{a.title}<small>{a.artist}</small></span></button>)}</div>}</div><button onClick={()=>zoom(1.2)}>＋</button><button onClick={()=>zoom(.82)}>－</button><button onClick={reset}>复位</button>{mode==='3d'&&<label>旋转 <input type="range" min="-80" max="80" value={camera.rotation} onChange={e=>setCamera(c=>({...c,rotation:+e.target.value}))}/></label>}</div><div className="relationScene" style={{transform:`translate(${camera.x}px,${camera.y}px) scale(${camera.scale})`}}><svg viewBox="-1100 -800 2200 1600">{edges.map(([i,j],k)=>{const a=project(points[albums[i].id],albums[i].id),b=project(points[albums[j].id],albums[j].id);return <line key={k} x1={a.x} y1={a.y} x2={b.x} y2={b.y}/>})}</svg>{albums.map(a=>{const p=project(points[a.id],a.id),depth=mode==='3d'?Math.max(.58,1+p.z/1300):1;return <button className={'relationNode '+(focus?.id===a.id?'active':'')} style={{left:p.x,top:p.y,transform:`translate(-50%,-50%) scale(${depth})`,zIndex:Math.round(p.z+900),opacity:mode==='3d'?Math.max(.4,.78+p.z/1100):1}} onPointerDown={e=>{e.stopPropagation();down(e,a.id)}} onClick={()=>select(a)} onDoubleClick={()=>select(a)} key={a.id}><img src={a.cover} alt=""/><b>{a.title}</b></button>})}</div>{focus&&<Focus a={focus} close={()=>setFocus(null)}/>}<div className="relationTrail"><span>探索轨迹</span>{trail.map(id=>{const a=all.find(x=>x.id===id);return a&&<button onClick={()=>select(a)} key={id}><img src={a.cover} alt={a.title}/></button>})}<button onClick={()=>setTrail([])}>清空</button></div><div className="dragHint">拖动画布 · 滚轮/双指缩放 · 拖动封面 · 方向键 / ± / 0 / Esc</div></div></main>}
function Focus({a,close}:{a:Album;close:()=>void}){const rank=a.ranks?.[0];return <aside className="relationFocus"><button onClick={close}>×</button><img src={a.cover} alt=""/><small>{a.year||'年份未知'} · {a.releaseType} · {a.language||'语言未知'}</small><h1>{a.title}</h1><h2>{a.artist}</h2><div className="focusStats"><span><b>{a.userRating||'—'}</b>个人 / 10</span><span><b>{a.communityRating||'—'}</b>RYM / 5</span><span><b>{a.trackCount}</b>曲目</span><span><b>{a.durationSeconds?Math.round(a.durationSeconds/60):'—'}</b>分钟</span><span><b>{a.ratingCount?.toLocaleString()}</b>评分</span><span><b>{rank?`#${rank.position}`:'—'}</b>榜单</span></div><h3>流派</h3><p>{a.genres.join(' · ')}</p><h3>标签</h3><p>{a.descriptors.join(' · ')}</p>{a.url&&<a href={a.url} target="_blank" rel="noreferrer">在 RYM 查看 ↗</a>}</aside>}
