'use client';
import {useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import * as THREE from 'three';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';

type Album={id:string;title:string;artist:string;cover:string};
type Edge={source:string;target:string;primary:boolean};
type Point={x:number;y:number;z:number;vx:number;vy:number;vz:number;fixed:boolean};
type Props={albums:Album[];edges:Edge[];depth:Map<string,number>;focusId:string;selectedId:string;onSelect:(id:string)=>void;onCenter:(id:string)=>void};

export default function ThreeGraph({albums,edges,depth,focusId,selectedId,onSelect,onCenter}:Props){
 const[panel,setPanel]=useState<HTMLElement|null>(null);
 const host=useRef<HTMLDivElement>(null),selectRef=useRef(onSelect),centerRef=useRef(onCenter),selectedRef=useRef(selectedId),paintRef=useRef<()=>void>(()=>{}),positionsRef=useRef(new Map<string,Point>()),cameraState=useRef<{position:THREE.Vector3;target:THREE.Vector3}|null>(null),textures=useRef(new Map<string,THREE.Texture>());
 useEffect(()=>{selectRef.current=onSelect;centerRef.current=onCenter;selectedRef.current=selectedId;paintRef.current()},[onSelect,onCenter,selectedId]);
 useEffect(()=>()=>{textures.current.forEach(texture=>texture.dispose());textures.current.clear()},[]);
 // The panel is rendered by the parent in the same commit; the follow-up render creates the portal inside it.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{setPanel(document.querySelector<HTMLElement>('.focusPanel'))},[focusId]);
 useEffect(()=>{
  const element=host.current;if(!element)return;
  const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x090908,.018);
  const camera=new THREE.PerspectiveCamera(44,1,.1,180),renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance',alpha:true});
  renderer.setPixelRatio(Math.min(2,devicePixelRatio||1));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.setClearColor(0x090908,0);element.appendChild(renderer.domElement);
  const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.08;controls.minDistance=7;controls.maxDistance=75;controls.zoomToCursor=true;if(cameraState.current){camera.position.copy(cameraState.current.position);controls.target.copy(cameraState.current.target)}else if(innerWidth<=800)camera.position.set(22,17,27);else camera.position.set(14,11,17);controls.update();
  const children=new Map(albums.map(a=>[a.id,[] as string[]])),parents=new Map<string,string>();edges.forEach(e=>{children.get(e.source)?.push(e.target);parents.set(e.target,e.source)});
  const seeded=new Map<string,Point>([[focusId,{x:0,y:0,z:0,vx:0,vy:0,vz:0,fixed:false}]]),hash=(s:string)=>{let h=2166136261;for(const c of s)h=Math.imul(h^c.charCodeAt(0),16777619);return(h>>>0)/4294967295};
  const place=(id:string)=>{const branch=children.get(id)||[],p=seeded.get(id)!,level=depth.get(id)||0,r=level===0?2.1:Math.max(.95,.82+branch.length*.075),phase=hash(id)*Math.PI*2;branch.forEach((child,i)=>{const y=1-2*(i+.5)/branch.length,ring=Math.sqrt(Math.max(0,1-y*y)),angle=phase+i*2.399963;seeded.set(child,{x:p.x+Math.cos(angle)*ring*r,y:p.y+y*r,z:p.z+Math.sin(angle)*ring*r,vx:0,vy:0,vz:0,fixed:false});place(child)})};place(focusId);
  const previous=positionsRef.current,changingCenter=previous.size>0,points=changingCenter?new Map(albums.map(album=>{const p=previous.get(album.id)||seeded.get(album.id)!;return[album.id,{...p,vx:0,vy:0,vz:0,fixed:false}]})):seeded;positionsRef.current=points;
  const subtree=(root:string)=>{if(root===focusId)return new Set([focusId,...(children.get(focusId)||[])]);const ids=new Set([root]),queue=[root];while(queue.length){const id=queue.shift()!;(children.get(id)||[]).forEach(child=>{if(!ids.has(child)){ids.add(child);queue.push(child)}})}let ancestor=root;while(parents.has(ancestor)){ancestor=parents.get(ancestor)!;ids.add(ancestor)}return ids};
  const descendants=(root:string)=>{const ids:string[]=[],queue=[root];while(queue.length){const id=queue.shift()!;(children.get(id)||[]).forEach(child=>{ids.push(child);queue.push(child)})}return ids};
  const first=new Set(children.get(focusId)||[]),sprites=new Map<string,THREE.Sprite>(),outlines=new Map<string,THREE.Sprite>(),nodes=new THREE.Group(),outlineGroup=new THREE.Group();scene.add(nodes,outlineGroup);
  const borderCanvas=document.createElement('canvas');borderCanvas.width=256;borderCanvas.height=256;const bc=borderCanvas.getContext('2d')!;bc.strokeStyle='#f1efe8';bc.lineWidth=7;bc.strokeRect(5,5,246,246);const borderTexture=new THREE.CanvasTexture(borderCanvas),loader=new THREE.TextureLoader();
  albums.forEach(a=>{let texture=textures.current.get(a.id);if(!texture){texture=loader.load(a.cover);texture.colorSpace=THREE.SRGBColorSpace;textures.current.set(a.id,texture)}const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:texture,transparent:true,alphaTest:.01,depthTest:true,depthWrite:true})),role=a.id===focusId?'center':first.has(a.id)?'neighbor':'secondary',scale=role==='center'?3.5:role==='neighbor'?2.35:1.55;sprite.scale.set(scale,scale,1);sprite.userData={id:a.id};nodes.add(sprite);sprites.set(a.id,sprite);const outline=new THREE.Sprite(new THREE.SpriteMaterial({map:borderTexture,transparent:true,depthTest:true,depthWrite:false}));outline.scale.copy(sprite.scale).multiplyScalar(1.045);outline.renderOrder=6;outlineGroup.add(outline);outlines.set(a.id,outline)});
  const edgeGroup=new THREE.Group();scene.add(edgeGroup);edges.forEach(e=>{const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(new Float32Array(6),3));const line=new THREE.Line(geometry,new THREE.LineBasicMaterial({color:e.primary?0xd8ff3e:0xffffff,transparent:true,opacity:e.primary?.68:.13}));line.userData=e;edgeGroup.add(line)});
  let hoverId:string|null=null;
  const setFog=(material:THREE.SpriteMaterial|THREE.LineBasicMaterial,fog:boolean)=>{if(material.fog!==fog){material.fog=fog;material.needsUpdate=true}};
  const paint=()=>{const selected=selectedRef.current,highlighted=subtree(hoverId||selected);sprites.forEach((sprite,id)=>{const p=points.get(id)!,lit=highlighted.has(id),fogExempt=id===focusId||first.has(id);sprite.position.set(p.x,p.y,p.z);setFog(sprite.material,!fogExempt);sprite.material.color.setHex(!lit?0x777777:0xffffff);sprite.material.opacity=!lit?.38:1;sprite.renderOrder=lit?4:2;const outline=outlines.get(id)!;outline.position.copy(sprite.position);outline.scale.copy(sprite.scale).multiplyScalar(id===selected?1.065:1.045);setFog(outline.material,!fogExempt);outline.material.color.setHex(id===focusId||id===selected||id===hoverId?0xd8ff3e:0xf1efe8);outline.material.opacity=!lit?.12:.72});edgeGroup.children.forEach(object=>{const line=object as THREE.Line,edge=line.userData as Edge,a=points.get(edge.source)!,b=points.get(edge.target)!,array=(line.geometry.attributes.position as THREE.BufferAttribute).array as Float32Array;array.set([a.x,a.y,a.z,b.x,b.y,b.z]);line.geometry.attributes.position.needsUpdate=true;const lit=highlighted.has(edge.source)&&highlighted.has(edge.target),material=line.material as THREE.LineBasicMaterial;setFog(material,!edge.primary);material.color.setHex(lit?0xd8ff3e:0xffffff);material.opacity=lit?.9:.055})};paintRef.current=paint;paint();
  let simulationFrame=0,ticks=0,energy=1,drag:null|{id:string;pointer:number;plane:THREE.Plane;moved:boolean;x:number;y:number;last:THREE.Vector3;descendants:string[]}=null,suppress=0,cameraFollowCenter=changingCenter;
  let simulationSpeed=changingCenter?.02:1;
  const simulate=()=>{ticks++;const timeScale=simulationSpeed<1?simulationSpeed+(1-simulationSpeed)*Math.min(1,ticks/180)**2:1,list=[...points.values()];for(let i=0;i<list.length;i++)for(let j=i+1;j<list.length;j++){const a=list[i],b=list[j],dx=b.x-a.x,dy=b.y-a.y,dz=b.z-a.z,d2=Math.max(.24,dx*dx+dy*dy+dz*dz),d=Math.sqrt(d2),f=Math.min(.018,.11/d2)*timeScale;if(!a.fixed){a.vx-=dx/d*f;a.vy-=dy/d*f;a.vz-=dz/d*f}if(!b.fixed){b.vx+=dx/d*f;b.vy+=dy/d*f;b.vz+=dz/d*f}}edges.forEach(e=>{const a=points.get(e.source)!,b=points.get(e.target)!,dx=b.x-a.x,dy=b.y-a.y,dz=b.z-a.z,d=Math.max(.01,Math.hypot(dx,dy,dz)),wanted=e.primary?2.1:(depth.get(e.target)||0)>=3?.85:1.15,f=(d-wanted)*.016*timeScale;if(!a.fixed){a.vx+=dx/d*f;a.vy+=dy/d*f;a.vz+=dz/d*f}if(!b.fixed){b.vx-=dx/d*f;b.vy-=dy/d*f;b.vz-=dz/d*f}});let movement=0;const damping=Math.pow(.82,timeScale);points.forEach((p,id)=>{if(p.fixed)return;const g=(id===focusId?.028:.002)*timeScale;p.vx-=p.x*g;p.vy-=p.y*g;p.vz-=p.z*g;p.vx*=damping;p.vy*=damping;p.vz*=damping;p.x+=p.vx*timeScale;p.y+=p.vy*timeScale;p.z+=p.vz*timeScale;movement+=(Math.abs(p.vx)+Math.abs(p.vy)+Math.abs(p.vz))*timeScale});paint();energy*=.995;if(drag||ticks<1100&&(movement>.002||energy>.008))simulationFrame=requestAnimationFrame(simulate)};simulationFrame=requestAnimationFrame(simulate);
  const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),intersection=new THREE.Vector3(),cameraDirection=new THREE.Vector3();const hit=(event:PointerEvent)=>{const r=renderer.domElement.getBoundingClientRect();pointer.set((event.clientX-r.left)/r.width*2-1,-((event.clientY-r.top)/r.height)*2+1);raycaster.setFromCamera(pointer,camera);return raycaster.intersectObjects([...sprites.values()],false)[0]?.object as THREE.Sprite|undefined};
  const down=(event:PointerEvent)=>{if(event.button!==0)return;const sprite=hit(event);if(!sprite)return;event.preventDefault();event.stopPropagation();cameraFollowCenter=false;simulationSpeed=1;const id=String(sprite.userData.id),p=points.get(id)!,childIds=descendants(id);hoverId=id;paint();camera.getWorldDirection(cameraDirection);drag={id,pointer:event.pointerId,plane:new THREE.Plane().setFromNormalAndCoplanarPoint(cameraDirection.clone(),sprite.position),moved:false,x:event.clientX,y:event.clientY,last:sprite.position.clone(),descendants:childIds};p.fixed=true;p.vx=p.vy=p.vz=0;childIds.forEach(childId=>{const child=points.get(childId)!;child.fixed=true;child.vx=child.vy=child.vz=0});controls.enabled=false;renderer.domElement.setPointerCapture(event.pointerId);renderer.domElement.style.cursor='grabbing'};
  const move=(event:PointerEvent)=>{if(!drag){const id=String(hit(event)?.userData.id||'')||null;if(id!==hoverId){hoverId=id;paint()}renderer.domElement.style.cursor=id?'pointer':'grab';return}if(drag.pointer!==event.pointerId)return;drag.moved||=Math.hypot(event.clientX-drag.x,event.clientY-drag.y)>4;const r=renderer.domElement.getBoundingClientRect();pointer.set((event.clientX-r.left)/r.width*2-1,-((event.clientY-r.top)/r.height)*2+1);raycaster.setFromCamera(pointer,camera);if(raycaster.ray.intersectPlane(drag.plane,intersection)){const delta=intersection.clone().sub(drag.last),p=points.get(drag.id)!;p.x=intersection.x;p.y=intersection.y;p.z=intersection.z;p.vx=p.vy=p.vz=0;drag.descendants.forEach(id=>{const child=points.get(id)!;child.x+=delta.x;child.y+=delta.y;child.z+=delta.z;child.vx=child.vy=child.vz=0});drag.last.copy(intersection);paint()}};
  const up=(event:PointerEvent)=>{if(!drag||drag.pointer!==event.pointerId)return;const d=drag;points.get(d.id)!.fixed=false;d.descendants.forEach(id=>{points.get(id)!.fixed=false});drag=null;controls.enabled=true;renderer.domElement.style.cursor='pointer';if(!d.moved)selectRef.current(d.id);else{suppress=performance.now()+180;energy=.4;ticks=0;simulationSpeed=1;cancelAnimationFrame(simulationFrame);simulationFrame=requestAnimationFrame(simulate)}};
  const leave=()=>{if(!drag){hoverId=null;paint()}},dbl=(event:MouseEvent)=>{if(performance.now()<suppress)return;const sprite=hit(event as PointerEvent);if(sprite)centerRef.current(String(sprite.userData.id))};renderer.domElement.addEventListener('pointerdown',down,true);renderer.domElement.addEventListener('pointermove',move,true);renderer.domElement.addEventListener('pointerup',up,true);renderer.domElement.addEventListener('pointercancel',up,true);renderer.domElement.addEventListener('pointerleave',leave);renderer.domElement.addEventListener('dblclick',dbl);
  controls.addEventListener('start',()=>{cameraFollowCenter=false});
  const resize=()=>{const width=element.clientWidth,height=element.clientHeight;if(!width||!height)return;renderer.setSize(width,height,false);camera.aspect=width/height;camera.updateProjectionMatrix()},observer=new ResizeObserver(resize);observer.observe(element);resize();let frame=0,alive=true;const animate=()=>{if(!alive)return;if(cameraFollowCenter){const focus=sprites.get(focusId);if(focus)controls.target.lerp(focus.position,.018)}controls.update();renderer.render(scene,camera);frame=requestAnimationFrame(animate)};animate();
  return()=>{alive=false;cameraState.current={position:camera.position.clone(),target:controls.target.clone()};paintRef.current=()=>{};cancelAnimationFrame(frame);cancelAnimationFrame(simulationFrame);observer.disconnect();controls.dispose();renderer.dispose();borderTexture.dispose();scene.traverse(o=>{if(o instanceof THREE.Sprite)o.material.dispose();if(o instanceof THREE.Line){o.geometry.dispose();(o.material as THREE.Material).dispose()}});renderer.domElement.remove()}
 },[albums,edges,depth,focusId]);
 return <>{panel&&createPortal(<button className="closePanel" type="button" aria-label="关闭专辑详情">×</button>,panel)}<div className="threeViewport" ref={host}/></>;
}
